# Generated by Django 5.2.8 on 2025-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_mascota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
