# Generated by Django 5.2.8 on 2025-12-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_mascota_observaciones_mascota_raza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.cliente'),
        ),
    ]
