# Generated by Django 5.2.8 on 2025-12-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_mascota_dueño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='dueño',
            new_name='cliente',
        ),
    ]
